openfoam: update to 21.06
Finally a working build :)

Tests done: run cavity tutorial on aarch64 and arm.

TODO/things that would be nice to test:

* Check if we actually need to set WM_{CC,CXX,CFLAGS,CXXFLAGS} in
  etc/config.sh/settings.
* Test compilation with Gcc on device
* Look at the __libc_malloc->malloc patch in sigFpe.C again, and try
  to upstream the fix so that it isn't as glibc specific.

We need to remove -std=c++11 from CXXFLAGS, or else we get errors when building with
our (rather new) version of CGAL, for example:

/data/data/com.termux/files/usr/include/CGAL/array.h:72:44: error: no template named 'index_sequence' in namespace 'std'
make_filled_array_aux(const T& value, std::index_sequence<Is...>)
                                      ~~~~~^

/data/data/com.termux/files/usr/include/CGAL/number_utils.h:320:10: warning: 'decltype(auto)' type specifier is a C++14 extension [-Wc++14-extensions]
  decltype(auto) approximate_sqrt(const NT& nt)
           ^
/data/data/com.termux/files/usr/include/CGAL/number_utils.h:320:1: error: deduced return types are a C++14 extension
  decltype(auto) approximate_sqrt(const NT& nt)
  ^